version: '3.4'

networks:
  grupo-7:

volumes:
  grupo-7-keycloak-data:
    external: true

services:
  # Keycloak
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - 8090:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=a12345678
      - KEYCLOAK_FRONTEND_URL=http://localhost:8090/auth
    networks:
      - grupo-7
  # REST API    
  rest-api:
    restart: on-failure
    container_name: microservices
    image: rest-api-ms
    ports:
      - 3000:3000
    networks:
     - grupo-7  